/*
[총 70건의 더미 데이터 생성]
=> 적격 50건 (ana_001 ~ ana_050)
=> 부적격 20건 (ana_051 ~ ana_070)

1) analysisId: id
2) date: 일자
3) merchantName: 거래처
4) itemName: 거래내용
5) amount: 금액

6) expenseCategory: 경비항목
- 제세공과금: TAXES_AND_DUES
- 임차료: RENT
- 기업업무추진비: BUSINESS_PROMOTION_EXPENSE
- 차량유지비: VEHICLE_MAINTENANCE
- 지급수수료: SERVICE_FEES
- 소모품비: SUPPLIES
- 운반비: DELIVERY_EXPENSE
- 광고선전비: ADVERTISING_EXPENSE
- 여비교통비: TRAVEL_AND_TRANSPORTATION
- 기타(비용): OTHER_EXPENSE

7) evidenceType: 증빙유형
- 세금계산서: TAX_INVOICE
- 계산서: INVOICE
- 신용카드 매출전표: CARD_RECEIPT
- 현금영수증: CASH_RECEIPT
- 해당 없음: NON_QUALIFIED (부적격 20건)


8) qualifiedEvidence: 적격여부
- 적격: true
- 부적격: false (부적격 20건)

9) aiReason: AI 판단

10) aiReli: AI 신뢰도
- 높음: HIGH
- 중간: MEDIUM
- 낮음: LOW

*/

export const mockTransactions = [
  {
    analysisId: "ana_001",
    date: "2026-08-01",
    merchantName: "스타벅스",
    itemName: "거래처 미팅 음료",
    amount: 12000,
    expenseCategory: "BUSINESS_PROMOTION_EXPENSE",
    evidenceType: "CARD_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "거래처와의 업무 미팅에 사용된 비용으로 판단됩니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_002",
    date: "2026-08-01",
    merchantName: "다이소",
    itemName: "사무용품",
    amount: 18500,
    expenseCategory: "SUPPLIES",
    evidenceType: "CARD_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "사업에 필요한 소모품 구입으로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_003",
    date: "2026-08-02",
    merchantName: "카카오T",
    itemName: "택시",
    amount: 15800,
    expenseCategory: "TRAVEL_AND_TRANSPORTATION",
    evidenceType: "CARD_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "업무 목적의 이동에 사용된 교통비로 판단됩니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_004",
    date: "2026-08-02",
    merchantName: "AWS",
    itemName: "클라우드 서버 이용료",
    amount: 45200,
    expenseCategory: "SERVICE_FEES",
    evidenceType: "TAX_INVOICE",
    qualifiedEvidence: true,
    aiReason: "업무용 클라우드 서비스 이용료로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_005",
    date: "2026-08-03",
    merchantName: "쿠팡",
    itemName: "포장용품",
    amount: 32900,
    expenseCategory: "DELIVERY_EXPENSE",
    evidenceType: "CASH_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "사업 상품의 포장 및 배송에 사용되는 비용으로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_006",
    date: "2026-08-03",
    merchantName: "네이버페이",
    itemName: "온라인 광고비",
    amount: 55000,
    expenseCategory: "ADVERTISING_EXPENSE",
    evidenceType: "CARD_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "사업 홍보를 위한 온라인 광고비로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_007",
    date: "2026-08-04",
    merchantName: "공유오피스",
    itemName: "사무실 이용료",
    amount: 220000,
    expenseCategory: "RENT",
    evidenceType: "TAX_INVOICE",
    qualifiedEvidence: true,
    aiReason: "업무 공간 임차에 대한 비용으로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_008",
    date: "2026-08-04",
    merchantName: "서울교통공사",
    itemName: "지하철 교통비",
    amount: 1500,
    expenseCategory: "TRAVEL_AND_TRANSPORTATION",
    evidenceType: "CARD_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "업무 목적의 교통비로 판단되나 사용 목적 확인이 필요합니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_009",
    date: "2026-08-05",
    merchantName: "문구점 알파",
    itemName: "노트 및 펜",
    amount: 14200,
    expenseCategory: "SUPPLIES",
    evidenceType: "CASH_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "업무용 문구류 구입으로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_010",
    date: "2026-08-05",
    merchantName: "우체국",
    itemName: "등기 우편 발송",
    amount: 6800,
    expenseCategory: "DELIVERY_EXPENSE",
    evidenceType: "CASH_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "업무 관련 서류 발송에 따른 운반비로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_011",
    date: "2026-08-06",
    merchantName: "SKT",
    itemName: "휴대전화 요금",
    amount: 69000,
    expenseCategory: "SERVICE_FEES",
    evidenceType: "TAX_INVOICE",
    qualifiedEvidence: true,
    aiReason: "통신 서비스 이용료로 판단되며 사업 사용 비율 확인이 필요합니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_012",
    date: "2026-08-06",
    merchantName: "GS25",
    itemName: "업무용 간식",
    amount: 8700,
    expenseCategory: "OTHER_EXPENSE",
    evidenceType: "CASH_RECEIPT",
    qualifiedEvidence: true,
    aiReason:
      "업무 중 발생한 비용으로 판단되나 구체적인 사용 목적 확인이 필요합니다.",
    aiReli: "LOW",
  },
  {
    analysisId: "ana_013",
    date: "2026-08-07",
    merchantName: "롯데렌탈",
    itemName: "차량 렌탈료",
    amount: 480000,
    expenseCategory: "VEHICLE_MAINTENANCE",
    evidenceType: "TAX_INVOICE",
    qualifiedEvidence: true,
    aiReason: "업무용 차량 관련 비용으로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_014",
    date: "2026-08-07",
    merchantName: "현대오일뱅크",
    itemName: "차량 주유",
    amount: 65000,
    expenseCategory: "VEHICLE_MAINTENANCE",
    evidenceType: "CARD_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "차량 운행에 따른 유류비로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_015",
    date: "2026-08-08",
    merchantName: "카페 레이어드",
    itemName: "미팅 음료",
    amount: 24000,
    expenseCategory: "BUSINESS_PROMOTION_EXPENSE",
    evidenceType: "INVOICE",
    qualifiedEvidence: true,
    aiReason:
      "업무 미팅 관련 지출로 판단되나 참석자 및 업무 목적 확인이 필요합니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_016",
    date: "2026-08-08",
    merchantName: "Adobe",
    itemName: "Creative Cloud 구독료",
    amount: 78000,
    expenseCategory: "SERVICE_FEES",
    evidenceType: "TAX_INVOICE",
    qualifiedEvidence: true,
    aiReason: "업무용 디자인 소프트웨어 구독료로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_017",
    date: "2026-08-09",
    merchantName: "교보문고",
    itemName: "업무 관련 서적",
    amount: 32000,
    expenseCategory: "SUPPLIES",
    evidenceType: "CARD_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "업무와 관련된 도서 구입으로 판단됩니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_018",
    date: "2026-08-09",
    merchantName: "대한항공",
    itemName: "출장 항공권",
    amount: 186000,
    expenseCategory: "TRAVEL_AND_TRANSPORTATION",
    evidenceType: "INVOICE",
    qualifiedEvidence: true,
    aiReason: "업무 목적의 출장에 따른 교통비로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_019",
    date: "2026-08-10",
    merchantName: "호텔신라",
    itemName: "출장 숙박비",
    amount: 145000,
    expenseCategory: "TRAVEL_AND_TRANSPORTATION",
    evidenceType: "TAX_INVOICE",
    qualifiedEvidence: true,
    aiReason: "업무 출장 중 발생한 숙박비로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_020",
    date: "2026-08-10",
    merchantName: "국세청",
    itemName: "사업 관련 세금",
    amount: 125000,
    expenseCategory: "TAXES_AND_DUES",
    evidenceType: "TAX_INVOICE",
    qualifiedEvidence: true,
    aiReason: "사업과 관련된 세금 및 공과금으로 판단됩니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_021",
    date: "2026-08-11",
    merchantName: "카카오페이",
    itemName: "플랫폼 이용 수수료",
    amount: 27000,
    expenseCategory: "SERVICE_FEES",
    evidenceType: "CARD_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "사업 플랫폼 이용에 따른 수수료로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_022",
    date: "2026-08-11",
    merchantName: "배달의민족",
    itemName: "업무용 식사",
    amount: 18500,
    expenseCategory: "BUSINESS_PROMOTION_EXPENSE",
    evidenceType: "CASH_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "업무 관련 식사 비용으로 판단되나 업무 관련성 확인이 필요합니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_023",
    date: "2026-08-12",
    merchantName: "한국전력",
    itemName: "전기요금",
    amount: 58000,
    expenseCategory: "TAXES_AND_DUES",
    evidenceType: "TAX_INVOICE",
    qualifiedEvidence: true,
    aiReason: "사업장 전기 사용에 따른 공과금으로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_024",
    date: "2026-08-12",
    merchantName: "삼성전자",
    itemName: "모니터",
    amount: 389000,
    expenseCategory: "SUPPLIES",
    evidenceType: "CARD_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "업무용 장비 구입으로 판단되며 자산 처리 여부 확인이 필요합니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_025",
    date: "2026-08-13",
    merchantName: "오늘의집",
    itemName: "책상 의자",
    amount: 215000,
    expenseCategory: "RENT",
    evidenceType: "INVOICE",
    qualifiedEvidence: true,
    aiReason: "업무 공간에서 사용하는 비품 관련 비용으로 판단됩니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_026",
    date: "2026-08-13",
    merchantName: "네이버",
    itemName: "검색 광고비",
    amount: 110000,
    expenseCategory: "ADVERTISING_EXPENSE",
    evidenceType: "TAX_INVOICE",
    qualifiedEvidence: true,
    aiReason: "사업 홍보를 위한 검색 광고비로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_027",
    date: "2026-08-14",
    merchantName: "토스",
    itemName: "송금 수수료",
    amount: 1500,
    expenseCategory: "SERVICE_FEES",
    evidenceType: "INVOICE",
    qualifiedEvidence: true,
    aiReason: "사업 관련 금융 거래에 따른 수수료로 판단됩니다.",
    aiReli: "LOW",
  },
  {
    analysisId: "ana_028",
    date: "2026-08-14",
    merchantName: "GS칼텍스",
    itemName: "차량 주유",
    amount: 72000,
    expenseCategory: "VEHICLE_MAINTENANCE",
    evidenceType: "CASH_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "업무용 차량의 유류비로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_029",
    date: "2026-08-15",
    merchantName: "쿠팡",
    itemName: "촬영용 조명",
    amount: 89000,
    expenseCategory: "SUPPLIES",
    evidenceType: "CARD_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "콘텐츠 제작에 사용하는 업무용 장비로 판단됩니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_030",
    date: "2026-08-15",
    merchantName: "우아한형제들",
    itemName: "배달 플랫폼 수수료",
    amount: 43000,
    expenseCategory: "DELIVERY_EXPENSE",
    evidenceType: "INVOICE",
    qualifiedEvidence: true,
    aiReason: "사업 운영에 따른 플랫폼 수수료로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_031",
    date: "2026-08-16",
    merchantName: "서울시",
    itemName: "사업 관련 공과금",
    amount: 34000,
    expenseCategory: "TAXES_AND_DUES",
    evidenceType: "CASH_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "사업 운영과 관련된 공과금으로 판단됩니다.",
    aiReli: "LOW",
  },
  {
    analysisId: "ana_032",
    date: "2026-08-16",
    merchantName: "카카오T",
    itemName: "출장 택시비",
    amount: 22100,
    expenseCategory: "TRAVEL_AND_TRANSPORTATION",
    evidenceType: "CARD_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "업무 목적의 출장에 따른 교통비로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_033",
    date: "2026-08-17",
    merchantName: "이마트",
    itemName: "사무용품",
    amount: 27300,
    expenseCategory: "SUPPLIES",
    evidenceType: "TAX_INVOICE",
    qualifiedEvidence: true,
    aiReason: "사업에 필요한 소모품 구입으로 판단됩니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_034",
    date: "2026-08-17",
    merchantName: "페이스북",
    itemName: "SNS 광고비",
    amount: 97000,
    expenseCategory: "ADVERTISING_EXPENSE",
    evidenceType: "INVOICE",
    qualifiedEvidence: true,
    aiReason: "사업 홍보 목적의 SNS 광고비로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_035",
    date: "2026-08-18",
    merchantName: "카페 드롭탑",
    itemName: "거래처 미팅",
    amount: 31500,
    expenseCategory: "BUSINESS_PROMOTION_EXPENSE",
    evidenceType: "CASH_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "거래처와의 업무 미팅에 사용된 비용으로 판단됩니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_036",
    date: "2026-08-18",
    merchantName: "한진택배",
    itemName: "상품 배송비",
    amount: 12600,
    expenseCategory: "DELIVERY_EXPENSE",
    evidenceType: "CASH_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "사업 상품 배송에 따른 운반비로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_037",
    date: "2026-08-19",
    merchantName: "KT",
    itemName: "인터넷 요금",
    amount: 38500,
    expenseCategory: "SERVICE_FEES",
    evidenceType: "TAX_INVOICE",
    qualifiedEvidence: true,
    aiReason: "업무용 인터넷 서비스 이용료로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_038",
    date: "2026-08-19",
    merchantName: "SK렌터카",
    itemName: "차량 대여료",
    amount: 132000,
    expenseCategory: "VEHICLE_MAINTENANCE",
    evidenceType: "INVOICE",
    qualifiedEvidence: true,
    aiReason: "업무 목적의 차량 대여 비용으로 판단됩니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_039",
    date: "2026-08-20",
    merchantName: "교보문고",
    itemName: "업무 참고서",
    amount: 28000,
    expenseCategory: "SUPPLIES",
    evidenceType: "CASH_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "업무 관련 도서 구입 비용으로 판단됩니다.",
    aiReli: "LOW",
  },
  {
    analysisId: "ana_040",
    date: "2026-08-20",
    merchantName: "네이버 클라우드",
    itemName: "서버 이용료",
    amount: 63000,
    expenseCategory: "SERVICE_FEES",
    evidenceType: "TAX_INVOICE",
    qualifiedEvidence: true,
    aiReason: "서비스 운영에 필요한 서버 이용료로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_041",
    date: "2026-08-21",
    merchantName: "GS25",
    itemName: "생수 및 음료",
    amount: 6200,
    expenseCategory: "OTHER_EXPENSE",
    evidenceType: "CARD_RECEIPT",
    qualifiedEvidence: true,
    aiReason:
      "업무 중 발생한 음료 비용으로 판단되나 사용 목적 확인이 필요합니다.",
    aiReli: "LOW",
  },
  {
    analysisId: "ana_042",
    date: "2026-08-21",
    merchantName: "한국철도공사",
    itemName: "KTX 승차권",
    amount: 59800,
    expenseCategory: "TRAVEL_AND_TRANSPORTATION",
    evidenceType: "INVOICE",
    qualifiedEvidence: true,
    aiReason: "업무 목적의 출장에 따른 철도 교통비로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_043",
    date: "2026-08-22",
    merchantName: "오늘의집",
    itemName: "촬영 배경 소품",
    amount: 47000,
    expenseCategory: "OTHER_EXPENSE",
    evidenceType: "CASH_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "콘텐츠 제작을 위한 소품 구입 비용으로 판단됩니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_044",
    date: "2026-08-22",
    merchantName: "네이버페이",
    itemName: "프로모션 비용",
    amount: 76000,
    expenseCategory: "ADVERTISING_EXPENSE",
    evidenceType: "INVOICE",
    qualifiedEvidence: true,
    aiReason: "사업 홍보 및 판매 촉진을 위한 광고비로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_045",
    date: "2026-08-23",
    merchantName: "서울도시가스",
    itemName: "가스 요금",
    amount: 42000,
    expenseCategory: "TAXES_AND_DUES",
    evidenceType: "TAX_INVOICE",
    qualifiedEvidence: true,
    aiReason: "사업장 사용에 따른 공과금으로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_046",
    date: "2026-08-23",
    merchantName: "카카오T",
    itemName: "거래처 방문 택시비",
    amount: 17400,
    expenseCategory: "TRAVEL_AND_TRANSPORTATION",
    evidenceType: "CARD_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "거래처 방문을 위한 업무 목적의 교통비로 판단됩니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_047",
    date: "2026-08-24",
    merchantName: "오피스디포",
    itemName: "프린터 잉크",
    amount: 38500,
    expenseCategory: "SUPPLIES",
    evidenceType: "CASH_RECEIPT",
    qualifiedEvidence: true,
    aiReason: "업무용 프린터에 사용되는 소모품으로 판단됩니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_048",
    date: "2026-08-24",
    merchantName: "카페베네",
    itemName: "업무 미팅 음료",
    amount: 13500,
    expenseCategory: "BUSINESS_PROMOTION_EXPENSE",
    evidenceType: "TAX_INVOICE",
    qualifiedEvidence: true,
    aiReason: "업무 미팅에 사용된 음료 비용으로 판단됩니다.",
    aiReli: "LOW",
  },
  {
    analysisId: "ana_049",
    date: "2026-08-25",
    merchantName: "삼성화재",
    itemName: "차량 보험료",
    amount: 185000,
    expenseCategory: "VEHICLE_MAINTENANCE",
    evidenceType: "INVOICE",
    qualifiedEvidence: true,
    aiReason: "사업용 차량과 관련된 보험료로 판단됩니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_050",
    date: "2026-08-25",
    merchantName: "네이버",
    itemName: "서비스 이용료",
    amount: 33000,
    expenseCategory: "OTHER_EXPENSE",
    evidenceType: "TAX_INVOICE",
    qualifiedEvidence: true,
    aiReason: "사업 운영과 관련된 서비스 이용 비용으로 판단됩니다.",
    aiReli: "LOW",
  },
  {
    analysisId: "ana_051",
    date: "2026-08-26",
    merchantName: "서울시",
    itemName: "사업 관련 지방세",
    amount: 42000,
    expenseCategory: "TAXES_AND_DUES",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason: "사업 관련 세금으로 보이나 적격 증빙이 확인되지 않았습니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_052",
    date: "2026-08-26",
    merchantName: "한국전력",
    itemName: "사업장 전기요금",
    amount: 68000,
    expenseCategory: "TAXES_AND_DUES",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason: "사업장 관련 공과금으로 보이나 적격 증빙이 확인되지 않았습니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_053",
    date: "2026-08-27",
    merchantName: "공유오피스",
    itemName: "사무실 월 이용료",
    amount: 198000,
    expenseCategory: "RENT",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason: "업무 공간 임차 비용으로 보이나 적격 증빙이 확인되지 않았습니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_054",
    date: "2026-08-27",
    merchantName: "스페이스클라우드",
    itemName: "회의실 대여료",
    amount: 55000,
    expenseCategory: "RENT",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason: "업무 공간 이용에 따른 임차료로 보이나 증빙 확인이 필요합니다.",
    aiReli: "LOW",
  },
  {
    analysisId: "ana_055",
    date: "2026-08-28",
    merchantName: "스타벅스",
    itemName: "거래처 미팅 음료",
    amount: 18500,
    expenseCategory: "BUSINESS_PROMOTION_EXPENSE",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason: "업무 미팅 관련 비용으로 보이나 적격 증빙이 확인되지 않았습니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_056",
    date: "2026-08-28",
    merchantName: "아웃백",
    itemName: "거래처 식사",
    amount: 87000,
    expenseCategory: "BUSINESS_PROMOTION_EXPENSE",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason:
      "거래처와의 업무 관련 식사 비용으로 보이나 증빙 확인이 필요합니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_057",
    date: "2026-08-29",
    merchantName: "현대오일뱅크",
    itemName: "차량 주유비",
    amount: 72000,
    expenseCategory: "VEHICLE_MAINTENANCE",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason: "업무용 차량의 유류비로 보이나 적격 증빙이 확인되지 않았습니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_058",
    date: "2026-08-29",
    merchantName: "카센터",
    itemName: "차량 정비비",
    amount: 135000,
    expenseCategory: "VEHICLE_MAINTENANCE",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason: "사업용 차량의 정비 비용으로 보이나 증빙 확인이 필요합니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_059",
    date: "2026-08-30",
    merchantName: "카카오페이",
    itemName: "플랫폼 이용 수수료",
    amount: 27000,
    expenseCategory: "SERVICE_FEES",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason:
      "사업 플랫폼 이용에 따른 수수료로 보이나 적격 증빙이 확인되지 않았습니다.",
    aiReli: "LOW",
  },
  {
    analysisId: "ana_060",
    date: "2026-08-30",
    merchantName: "토스",
    itemName: "송금 수수료",
    amount: 1500,
    expenseCategory: "SERVICE_FEES",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason: "사업 관련 금융 수수료로 보이나 적격 증빙이 확인되지 않았습니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_061",
    date: "2026-08-31",
    merchantName: "다이소",
    itemName: "사무용품",
    amount: 23000,
    expenseCategory: "SUPPLIES",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason:
      "사업에 사용되는 소모품으로 보이나 적격 증빙이 확인되지 않았습니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_062",
    date: "2026-08-31",
    merchantName: "문구점",
    itemName: "노트 및 필기구",
    amount: 16500,
    expenseCategory: "SUPPLIES",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason: "업무용 소모품으로 보이나 증빙 확인이 필요합니다.",
    aiReli: "LOW",
  },
  {
    analysisId: "ana_063",
    date: "2026-09-01",
    merchantName: "한진택배",
    itemName: "상품 배송비",
    amount: 12800,
    expenseCategory: "DELIVERY_EXPENSE",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason:
      "사업 상품 배송에 따른 운반비로 보이나 적격 증빙이 확인되지 않았습니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_064",
    date: "2026-09-01",
    merchantName: "우체국",
    itemName: "등기 우편 발송비",
    amount: 7200,
    expenseCategory: "DELIVERY_EXPENSE",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason: "업무 관련 우편 발송 비용으로 보이나 증빙 확인이 필요합니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_065",
    date: "2026-09-02",
    merchantName: "네이버",
    itemName: "검색 광고비",
    amount: 95000,
    expenseCategory: "ADVERTISING_EXPENSE",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason:
      "사업 홍보를 위한 광고비로 보이나 적격 증빙이 확인되지 않았습니다.",
    aiReli: "HIGH",
  },
  {
    analysisId: "ana_066",
    date: "2026-09-02",
    merchantName: "메타",
    itemName: "SNS 광고비",
    amount: 83000,
    expenseCategory: "ADVERTISING_EXPENSE",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason: "사업 홍보 목적의 광고비로 보이나 증빙 확인이 필요합니다.",
    aiReli: "LOW",
  },
  {
    analysisId: "ana_067",
    date: "2026-09-03",
    merchantName: "카카오T",
    itemName: "거래처 방문 택시비",
    amount: 18600,
    expenseCategory: "TRAVEL_AND_TRANSPORTATION",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason:
      "거래처 방문을 위한 교통비로 보이나 적격 증빙이 확인되지 않았습니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_068",
    date: "2026-09-03",
    merchantName: "한국철도공사",
    itemName: "출장 KTX 승차권",
    amount: 59800,
    expenseCategory: "TRAVEL_AND_TRANSPORTATION",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason: "업무 출장에 따른 교통비로 보이나 증빙 확인이 필요합니다.",
    aiReli: "LOW",
  },
  {
    analysisId: "ana_069",
    date: "2026-09-04",
    merchantName: "온라인 쇼핑몰",
    itemName: "업무 관련 구매",
    amount: 41000,
    expenseCategory: "OTHER_EXPENSE",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason:
      "사업 관련 비용으로 추정되나 구체적인 사용 목적과 증빙 확인이 필요합니다.",
    aiReli: "MEDIUM",
  },
  {
    analysisId: "ana_070",
    date: "2026-09-04",
    merchantName: "편의점",
    itemName: "기타 업무 비용",
    amount: 9800,
    expenseCategory: "OTHER_EXPENSE",
    evidenceType: "NON_QUALIFIED",
    qualifiedEvidence: false,
    aiReason:
      "사업 관련 비용인지 확인할 수 있는 정보와 적격 증빙이 부족합니다.",
    aiReli: "LOW",
  },
];
